- name: playbook for creating a bd L2
  hosts: '{{ site }}'
  gather_facts: no
  vars:
    aci_login: &aci_login
      host: '{{ ansible_host }}'
      username: '{{ ansible_user }}'
      password: '{{ password }}'
      validate_certs: no

  tasks:
    - name: Create a BD L2
      aci_bd:
        <<: *aci_login
        tenant: '{{ tenant }}'
        bd: '{{ bd }}'
        vrf: '{{ vrf }}'

        arp_flooding: yes
        enable_routing: no
        description: '{{ bd }}'
        mac_address: 00:22:BD:F8:19:FF
        l2_unknown_unicast: flood
       
        state: present
      delegate_to: localhost